server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

  - job_name: fmcg_logs

    static_configs:
      - targets:
          - localhost

        labels:
          job: fmcg_app
          service: api
          __path__: /var/log/fmcg/*.log

    pipeline_stages:

      - regex:
          expression: '^\[(?P<timestamp>.*?)\]\s+\|\s+level=(?P<level>\w+)\s+\|\s+request_id=(?P<request_id>.*?)\s+\|\s+module=(?P<module>.*?)\s+\|\s+function=(?P<function>.*?)\s+\|\s+line=(?P<line>\d+)\s+\|\s+message="?(?P<message>.*)"?$'

      - labels:
          level:
          module:
          function:
          request_id:

      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05,000'

      - output:
          source: message